### ISSUE TITLE
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed

### ISSUE THREAD

**Issue by humancalico** [pop-os/beta#12]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Upgraded from 19.10

**Issue/Bug Description:**
On doing a `sudo pop-upgrade release upgrade systemd -f` I ran into this problem which is similar to the issue Reddit issue described [here](https://www.reddit.com/r/pop_os/comments/fvuvla/pop_os_2004_with_xfce/fmkq3fc/)

```sh
Release upgrade status: release upgrade aborted: fetch of package 'libgdata22_0.17.12-1_amd64.deb' at http://us.archive.ubuntu.com/ubuntu/pool/main/libg/libgdata/libgdata22_0.17.12-1_amd64.deb failed: async fetch for "/var/cache/apt/archives/partial/libgdata22_0.17.12-1_amd64.deb" failed: http://us.archive.ubuntu.com/ubuntu/pool/main/libg/libgdata/libgdata22_0.17.12-1_amd64.deb: connection closed before message completed
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed
```

**Comment by Kartonrealista** [comment]
I encountered the same issue, you have to make sure you don't lose connection while the process is running. Try upgrading repeatedly and it should work after a couple tries. It seemed to me like the system going to sleep somehow affected this but that might have been just a coincidence.

**Comment by ghisvail** [comment]
Same here. Had to repeat the command a handful of times before all packages were downloaded. Sounds like the code behind it would benefit from a little bit of retry logic.

**Comment by humancalico** [comment]
@Kartonrealista @ghisvail It's still failing after several retries. What is the downside if I do a `do-release-upgrade` that @jackpot51 warned against it [here](https://www.reddit.com/r/pop_os/comments/fvhbfi/pop_os_2004_better_and_better/fmlyadx/)

**Comment by ghisvail** [comment]
I suppose there must be some reason(s) why Pop provides its own tool for performing release upgrades rather than using the Ubuntu one.

**Comment by Kartonrealista** [comment]
This is a beta, if the devs say "don't do this" then it's probably gonna break something and mess up reporting of actual issues with the system. You've got to excercise patience, and maybe try preventing your screen from going to sleep

**Comment by rchdz** [comment]
https://www.reddit.com/r/pop_os/comments/fwt2y6/wanting_to_test_out_pop_os_2004_but_cant/

**Comment by rsdundon** [comment]
Ran into the same issue with the v14 iso of 19.10 when I tried to upgrade to 20.04 Beta. Following in the instructions in the Reddit link above I was able to get fully graded to the Beta, but not with out issues.

Took 3 or 4 tries of the `sudo pop-upgrade release upgrade systemd -f` command to get through everything and get it all downloaded. It would error out and stop, making me try again. But persistence paid off and now the Beta is running and, so far, flawlessly. # #

**Comment by NoBackUp42** [comment]
Yep Reddit Steps solved it for me ... 
upgrade in place 19.10 V14 -> 20.04
VirtualBox 6.1.6 Windows 10 Host

**Comment by WatchMkr** [comment]
This should be fixed.

**Comment by raphaelcasimir** [comment]
Seems to work with the Reddit post... Thanks @rchdz for posting it here where it belongs.
FYI:

> *user:* allthatandmore
> That's a bug in the v13 ISO. For purposes of upgrading you can just run `sudo pop-upgrade daemon` then **open up a new terminal tab** and then execute the full [...] upgrade command.

This command is: `sudo pop-upgrade release upgrade systemd`

**Comment by rednafi** [comment]
Nope, it still persists while upgrading from pop 18.04 to 20.04.

**Comment by Haprog** [comment]
I just got this error when trying to upgrade from Pop!_OS 20.04 to 20.10.

**Comment by Haprog** [comment]
Actually this is what I get:
```
checking if pop-upgrade requires an update
Current Release: 20.04
Upgrading to: 20.10
New version available: 15
Event: updating package lists
Event: fetching updated packages for the current release
Release upgrade status: release upgrade aborted: failed to fetch apt URIs to fetch
pop-upgrade: dbus client error
  caused by: calling ReleaseUpgradeFinalize method failed
  caused by: "release upgrade cannot be finalized, because a release upgrade was not performed"
```
Though I have no problems running `sudo apt update` and `sudo apt upgrade` or `sudo apt full-upgrade`.

**Comment by Haprog** [comment]
In my case I guess the problem was some dependency issues (unmet dependencies) related to packages I had manually installed. I'm not sure if this is related to this issue directly, but I'm documenting what I did to get it fixed hoping it might help someone else. Though the exact packages I had to upgrade/downgrade might be different for you.

Good thing I had TimeShift installed and took a system snapshot before upgrade. I'd suggest anyone to do the same before trying to fix apt dependency issues. This came in handy as I had to restore from the snapshot couple of times as I wanted to try things differently from cleaner state where I hadn't tried to run the upgrade yet.

I was able to investigate my issues by following the instructions here: https://unix.stackexchange.com/a/616898 (though first I made sure all my apt sources were using `focal` 20.04 instead of `groovy` 20.10 so I could fix any issues in current 20.04 installation first). That finally gave me some hints about a few very random looking packages that had unmet dependencies which I then investigated further by running `apt-cache rdepends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --installed --recurse <package_name>` for each of the packages (command found here: https://askubuntu.com/questions/5636/can-i-see-why-a-package-is-installed#comment505140_5637).

I think one issue in my case was that I had installed some package that depends on `nodejs` but I had later manually removed the `nodejs` package with apt since I was using `nvm` to manage several installations of `nodejs`. I manually installed `nodejs` with apt again to get past this. Also I seemed to have some problems related to dependencies of apps that I had tried but didn't use/need anymore so I just removed those apps.

I still wasn't able to upgrade pop so I was trying to use some commands from these instructions:
- https://support.system76.com/articles/package-manager-pop/
- https://support.system76.com/articles/upgrade-pop/

After this when trying to run `sudo apt full-upgrade` it was trying to downgrade a lot of packages and wanted to also remove `pop-desktop` which it was warning about (as being an essential package). I'm now sure how but it seemed like I had somehow already got "too new" versions of some packages installed like `pop-desktop`, `gdm3`, `gnome-shell` so that running `apt-cache policy <package>` for several packages listed that I have a newer version installed than what is available from the `focal` repos. Maybe I had already tried the upgrade earlier from the GUI notification much earlier but it failed and I just forgot about it, but it had already updated some packages?

I ended up manually downgrading those with `sudo apt install <package>=<version>` which often complained about other issues with dependencies which I then also had to check and I build a long install command that explicitly installed specific versions of several related packages until it didn't complain anymore and was happy to downgrade those. Then in the end I was able to run `sudo apt full-upgrade` without it trying to remove `pop-desktop` anymore.

Here's some examples of what I had to run to get to a good working state so that apt full-upgrade and pop release upgrade didn't complain.
```
sudo apt install gvfs=1.44.1-1ubuntu1 gvfs-common=1.44.1-1ubuntu1 gvfs-daemons=1.44.1-1ubuntu1 gvfs-libs=1.44.1-1ubuntu1 gvfs-backends=1.44.1-1ubuntu1 gvfs-fuse=1.44.1-1ubuntu1  pop-desktop=1.4.1~1608319397~20.04~c878eae
sudo apt install gdm3=3.36.3-0ubuntu0.20.04.3pop0~1621627711~20.04~5b11755 gnome-settings-daemon=3.36.1-0ubuntu1pop0~1596026424~20.04~8296153 gnome-shell=3.36.7-0ubuntu0.20.04.1pop1~1614014876~20.04~4e7877a gnome-session-bin=3.36.0-2ubuntu1 pop-desktop
```

Then at some point I was able to run the steps from https://support.system76.com/articles/package-manager-pop/ without issues and it seemed that all packages were updated, and after that I was able to also run the upgrade (`pop-upgrade release upgrade`) and it seemed to finish correctly ending in "Release upgrade status: systems are go for launch: reboot now". Funnily after rebooting it seemed like I was still on focal 20.04 and running apt update and upgrade showed focal sources and no updates available, no issues. I tried again but still after rebooting the same issue (not upgraded).

Then I tried (after reboot again) `sudo do-release-upgrade` but that failed with this kind of error:
```
...
Original exception was:
Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-a84m0b4a/groovy", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-a84m0b4a/DistUpgrade/DistUpgradeMain.py", line 238, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-a84m0b4a/DistUpgrade/DistUpgradeController.py", line 2089, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-a84m0b4a/DistUpgrade/DistUpgradeController.py", line 1932, in fullUpgrade
    if not self.updateSourcesList():
  File "/tmp/ubuntu-release-upgrader-a84m0b4a/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesList
    self.sources = SourcesList(matcherPath=self.datadir)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__
    self.matcher = SourceEntryMatcher(matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__
    dist = DistInfo(base_dir=matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__
    with open(dist_fname) as dist_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ubuntu-release-upgrader-a84m0b4a/Pop.info'
```
This I was able to solve with [this workaround](https://askubuntu.com/a/1286533) by creating an empty `Pop.info` file and then hitting `r` key in the upgrade "screen" so it reruns it and this time the do-release-upgrade seemed to continue normally to installing packages.

After this struggle and rebooting I finally seem to have 20.10 with correct groovy apt sources and everything up to date according to apt.

**Comment by jacobgkau** [comment]
@Haprog, I'm sorry about the upgrade trouble.

> I had installed some package that depends on `nodejs` but I had later manually removed the `nodejs` package

It sounds like you may have had package manager issues present on your system before attempting to upgrade, if you intentionally removed a dependency without removing the dependent packages. Based on the original `pop-upgrade` error message:

> Release upgrade status: release upgrade aborted: failed to fetch apt URIs to fetch
> pop-upgrade: dbus client error
>   caused by: calling ReleaseUpgradeFinalize method failed
>   caused by: "release upgrade cannot be finalized, because a release upgrade was not performed"

The `failed to fetch apt URIs` part sounds more like a bad URL was present, which `sudo apt update` should have shown us at that time, but the entire thing together combined with none of the `apt` commands showing you any errors sounds more like a failed upgrade actually occurred _before_ you saw that particular output:

https://github.com/pop-os/upgrade/issues/147
https://github.com/pop-os/upgrade/issues/140
https://github.com/pop-os/upgrade/issues/138

The last issue in that list is still open, and it's in the `pop-upgrade` repository (this issue you commented in is in the Pop!_OS Beta repository, which is no longer applicable if you were trying to upgrade from 20.04 to 20.10.) If you're able to recreate this issue from a fresh installation of Pop 20.04, providing instructions to do so in https://github.com/pop-os/upgrade/issues/138 would help determine the cause and how to fix it; trying the development branch at https://github.com/pop-os/upgrade/pull/142 to see if the issue's still present there would also be helpful.
